# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sm1bnvPt14Tnz111Y5SA2VvSGY6C0nGQ
"""

import pandas as pd

import numpy as np

df=pd.read_csv('/content/customer_shopping_data.csv')

df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Convert invoice_date to datetime
df['invoice_date'] = pd.to_datetime(df['invoice_date'], dayfirst=True)

# 1. Calculate basic statistics
def calculate_statistics(data):
    stats_summary = data.describe().T
    stats_summary['mode'] = data.mode().iloc[0]
    stats_summary['median'] = data.median()
    return stats_summary

# Basic statistics
statistics = calculate_statistics(df[['age', 'quantity', 'price']])
print("Basic Statistics:\n", statistics)

# 2. Analyze sales trends over time
df['year_month'] = df['invoice_date'].dt.to_period('M')
monthly_sales = df.groupby('year_month')['price'].sum()

plt.figure(figsize=(10, 6))
plt.plot(monthly_sales.index.to_timestamp(), monthly_sales.values, marker='o')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

# 3. Customer and Product Analysis
# Customer demographics
customer_demographics = df.groupby('gender').agg({
    'customer_id': pd.Series.nunique,
    'age': ['mean', 'median'],
    'price': 'sum'
}).reset_index()
customer_demographics.columns = ['Gender', 'Unique Customers', 'Average Age', 'Median Age', 'Total Spend']

# Purchasing behavior
category_sales = df.groupby('category')['price'].sum().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=category_sales.index, y=category_sales.values)
plt.title('Sales by Product Category')
plt.xlabel('Category')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

# 4. Visualization
# Age distribution
plt.figure(figsize=(10, 6))
sns.histplot(df['age'], bins=20, kde=True)
plt.title('Age Distribution of Customers')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Heatmap of sales across categories and payment methods
category_payment = df.pivot_table(index='category', columns='payment_method', values='price', aggfunc='sum', fill_value=0)

plt.figure(figsize=(10, 6))
sns.heatmap(category_payment, annot=True, fmt='.2f', cmap='YlGnBu')
plt.title('Heatmap of Sales by Category and Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Category')
plt.show()

"""Based on the Exploratory Data Analysis (EDA) of the customer shopping data, here are some actionable recommendations:

Targeted Marketing for Age Groups:

The age distribution analysis shows significant customer presence in certain age groups. Tailor marketing campaigns to target these age groups more effectively. For example, if the majority of customers are between 20-30 years old, focus on products and promotions that appeal to this demographic.
Optimize Inventory for Popular Categories:

The bar chart of sales by product category indicates which categories generate the most revenue. Ensure that popular categories like Clothing and Shoes are well-stocked. Consider expanding the product range in these categories to maximize sales.
Enhance Payment Method Options:

The heatmap shows sales distribution across different payment methods. If certain payment methods like Credit Cards are more popular, ensure the checkout process for these methods is seamless and possibly offer incentives or discounts for using these methods to encourage higher sales.
Seasonal Sales Strategy:

The monthly sales trend analysis can help identify peak shopping periods. Use this information to plan seasonal sales, promotions, and stock management. For instance, if there are spikes in sales during certain months, prepare marketing campaigns and inventory in advance for those periods.
Loyalty Programs for High-Value Customers:

Identify customers with high total spend and consider implementing loyalty programs to retain these valuable customers. Offer them exclusive discounts, early access to new products, or special promotions to encourage repeat purchases.
Personalized Shopping Experience:

Use the customer demographics and purchasing behavior analysis to personalize the shopping experience. For example, recommend products based on past purchases, send personalized offers, and create targeted email campaigns.
Expand to High-Performing Malls:

Analyze the performance of different shopping malls based on the data. If certain malls like "Kanyon" or "Forum Istanbul" have higher sales, consider expanding the product range or running special promotions in these locations.
Improve Online Presence:

If the dataset includes online sales data, compare it with in-store sales. Strengthen online marketing efforts and optimize the online shopping experience to capture a larger share of the market, especially if online sales are growing.
Customer Feedback and Service:

Collect and analyze customer feedback regularly to understand their needs and preferences. Use this information to improve product offerings, customer service, and overall shopping experience.
Promotions on Low-Selling Categories:

For categories with lower sales, consider running special promotions or discounts to boost interest and sales. Additionally, analyze if there are any barriers to purchase in these categories and address them.
"""

